name: Publish to Harbor
on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login Harbor
      uses: docker/login-action@v1
      with:
        registry: harbor.ar2ro.io
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Build and push to harbor
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          harbor.ar2ro.io/destinyarena/registration:latest
