name: Build Image and Deploy
on:
  push:
    branches: master

jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login Harbor
      uses: docker/login-action@v1
      with:
        registry: harbor.ar2ro.io
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Build and push to harbor
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          harbor.ar2ro.io/destinyarena/registration:latest
          harbor.ar2ro.io/destinyarena/registration:${{ github.sha }}
    - name: Checkout Helm Repo
      uses: actions/checkout@v2
      with:
        repository: destinyarena/helm-charts
        token: ${{ secrets.DESTINYARENA_ACTIONS }}
    - name: Installs yq
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y
    - name: Update the Helm Chart values.yaml
      run: |
        yq w -i values.yaml registration.image.tag ${{ github.sha }}
    - name: Commit and Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Registration Tag: ${{ github.sha }}"
        git push origin master
